server.port=8080
gemini.api-key=${GEMINI_API_KEY:}
gcp.project-id=${GCP_PROJECT_ID:project-a0af5f0f-bd7b-47d8-98c}
gcp.location=${GCP_LOCATION:us-central1}
gcp.drive.folder-id=${GCP_DRIVE_FOLDER_ID:}
app.webhook-url=${APP_WEBHOOK_URL:https://doc-search-demo-454184802292.asia-northeast3.run.app/api/drive/webhook}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
